# Generated by Django 2.0.5 on 2018-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.CharField(max_length=200)),
                ('fitness', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
