# Generated by Django 2.0.5 on 2018-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='generation',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='population',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
