# Generated by Django 2.0.5 on 2018-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0002_auto_20180513_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/conrad/images'),
        ),
    ]
