# Generated by Django 2.0.5 on 2018-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0003_auto_20180516_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='fitness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
