# Generated by Django 2.0.5 on 2018-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0004_auto_20180518_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
