# Generated by Django 2.0.5 on 2018-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0005_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
