# Generated by Django 2.0.5 on 2018-05-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0006_auto_20180523_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='function',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
