# Generated by Django 2.0.5 on 2018-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0007_auto_20180530_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='gallery_fitness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
