# Generated by Django 2.0.5 on 2018-06-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0008_auto_20180604_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='father',
            field=models.ManyToManyField(default=None, related_name='_artist_father_+', to='conrad.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='mother',
            field=models.ManyToManyField(default=None, related_name='_artist_mother_+', to='conrad.Artist'),
        ),
    ]
