# Generated by Django 2.0.5 on 2018-06-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0009_auto_20180608_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image500',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
