# Generated by Django 2.0.5 on 2018-06-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0010_artist_image500'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
