# Generated by Django 2.0.6 on 2018-06-16 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0011_artist_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 16, 16, 18, 10, 519089, tzinfo=utc)),
        ),
    ]
