# Generated by Django 2.0.6 on 2018-06-21 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0012_auto_20180616_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='global_pop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 21, 15, 42, 52, 686280, tzinfo=utc)),
        ),
    ]
