# Generated by Django 2.0.6 on 2018-06-21 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0013_auto_20180621_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
