# Generated by Django 2.0.6 on 2018-06-22 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conrad', '0014_auto_20180621_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='gallery_voters',
            field=models.ManyToManyField(default=None, related_name='_artist_gallery_voters_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='voters',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
