# Generated by Django 2.0.6 on 2018-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conrad', '0015_auto_20180622_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='function',
        ),
    ]
